### ISSUE TITLE
how to compile so that a terminal bash script does not open on OSX ?

### ISSUE THREAD

**Issue by joeblew99** [peterhellberg/gophereyes#1]
you might know. Am hunting for answer..

**Comment by joeblew99** [comment]
just saw upx and macpack in the makefile.

can you let me know where to get this :)

**Comment by peterhellberg** [comment]
Yes, I should have added that to the README.md :)

```
go get -u github.com/murlokswarm/macpack
brew install upx
```

**Comment by peterhellberg** [comment]
Then you can run:

```sh
cd $GOPATH/src/github.com/peterhellberg/gophereyes
make upx-app
open build/GopherEyes.app
```

(or `make app` if you don't want to compress the binary)

**Comment by peterhellberg** [comment]
I've now added the instructions to the [README.md](https://github.com/peterhellberg/gophereyes#compilation-of-gophereyesapp)

**Comment by joeblew99** [comment]
:) thanks

I guess you know about this ???
https://en.wikipedia.org/wiki/UPX:
"Most antivirus products will raise an alarm when UPX header is detected"
